"""teams, passkeys, checkpoints, claims

Revision ID: 7bd2d286e2ae
Revises: 
Create Date: 2026-08-28 09:46:58.006187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7bd2d286e2ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('quorum_min_members', sa.Integer(), nullable=False),
    sa.Column('default_radius_m', sa.Integer(), nullable=False),
    sa.Column('max_accuracy_m', sa.Integer(), nullable=False),
    sa.Column('default_dwell_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communities_slug'), 'communities', ['slug'], unique=True)
    op.create_table('checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Integer(), nullable=True),
    sa.Column('dwell_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'sequence', name='uq_checkpoints_community_sequence'),
    sa.UniqueConstraint('community_id', 'slug', name='uq_checkpoints_community_slug')
    )
    op.create_index(op.f('ix_checkpoints_community_id'), 'checkpoints', ['community_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('team_code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'team_code', name='uq_teams_community_code')
    )
    op.create_index(op.f('ix_teams_community_id'), 'teams', ['community_id'], unique=False)
    op.create_index(op.f('ix_teams_team_code'), 'teams', ['team_code'], unique=False)
    op.create_table('checkpoint_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_id', sa.UUID(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'checkpoint_id', name='uq_progress_team_checkpoint')
    )
    op.create_index(op.f('ix_checkpoint_progress_checkpoint_id'), 'checkpoint_progress', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_checkpoint_progress_team_id'), 'checkpoint_progress', ['team_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('member_code', sa.String(length=8), nullable=False),
    sa.Column('passkey_hash', sa.String(length=64), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'member_code', name='uq_team_members_code')
    )
    op.create_index(op.f('ix_team_members_passkey_hash'), 'team_members', ['passkey_hash'], unique=True)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_table('checkpoint_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.String(length=32), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['team_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkpoint_claims_checkpoint_id'), 'checkpoint_claims', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_checkpoint_claims_member_id'), 'checkpoint_claims', ['member_id'], unique=False)
    op.create_index(op.f('ix_checkpoint_claims_team_id'), 'checkpoint_claims', ['team_id'], unique=False)
    op.create_index('ix_claims_checkpoint_team', 'checkpoint_claims', ['checkpoint_id', 'team_id'], unique=False)
    op.create_table('member_positions',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['team_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index(op.f('ix_member_positions_team_id'), 'member_positions', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_positions_team_id'), table_name='member_positions')
    op.drop_table('member_positions')
    op.drop_index('ix_claims_checkpoint_team', table_name='checkpoint_claims')
    op.drop_index(op.f('ix_checkpoint_claims_team_id'), table_name='checkpoint_claims')
    op.drop_index(op.f('ix_checkpoint_claims_member_id'), table_name='checkpoint_claims')
    op.drop_index(op.f('ix_checkpoint_claims_checkpoint_id'), table_name='checkpoint_claims')
    op.drop_table('checkpoint_claims')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_passkey_hash'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_checkpoint_progress_team_id'), table_name='checkpoint_progress')
    op.drop_index(op.f('ix_checkpoint_progress_checkpoint_id'), table_name='checkpoint_progress')
    op.drop_table('checkpoint_progress')
    op.drop_index(op.f('ix_teams_team_code'), table_name='teams')
    op.drop_index(op.f('ix_teams_community_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_checkpoints_community_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_communities_slug'), table_name='communities')
    op.drop_table('communities')
    # ### end Alembic commands ###
