"""add quorum window to community

Revision ID: ba130ce00da3
Revises: 7bd2d286e2ae
Create Date: 2026-08-28 09:57:26.087616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba130ce00da3'
down_revision: Union[str, None] = '7bd2d286e2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('quorum_window_seconds', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'quorum_window_seconds')
    # ### end Alembic commands ###
